# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'McEx.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(140, 10, 250, 345))
        self.groupBox.setObjectName("groupBox")
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget.setGeometry(QtCore.QRect(5, 20, 240, 271))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 310, 251, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(5, 0, 5, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnMineSell = QtWidgets.QPushButton(self.layoutWidget)
        self.btnMineSell.setMinimumSize(QtCore.QSize(32, 23))
        self.btnMineSell.setObjectName("btnMineSell")
        self.gridLayout.addWidget(self.btnMineSell, 0, 1, 1, 1)
        self.btnMineExChange = QtWidgets.QPushButton(self.layoutWidget)
        self.btnMineExChange.setMinimumSize(QtCore.QSize(32, 23))
        self.btnMineExChange.setObjectName("btnMineExChange")
        self.gridLayout.addWidget(self.btnMineExChange, 0, 2, 1, 1)
        self.btnMineReload = QtWidgets.QPushButton(self.layoutWidget)
        self.btnMineReload.setMinimumSize(QtCore.QSize(32, 23))
        self.btnMineReload.setObjectName("btnMineReload")
        self.gridLayout.addWidget(self.btnMineReload, 0, 3, 1, 1)
        self.btnMineBuy = QtWidgets.QPushButton(self.layoutWidget)
        self.btnMineBuy.setMinimumSize(QtCore.QSize(32, 23))
        self.btnMineBuy.setObjectName("btnMineBuy")
        self.gridLayout.addWidget(self.btnMineBuy, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuIfover = QtWidgets.QMenu(self.menuBar)
        self.menuIfover.setObjectName("menuIfover")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuIfover.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.btnMineSell.setText(_translate("MainWindow", "卖"))
        self.btnMineExChange.setText(_translate("MainWindow", "换"))
        self.btnMineReload.setText(_translate("MainWindow", "刷"))
        self.btnMineBuy.setText(_translate("MainWindow", "买"))
        self.menuIfover.setTitle(_translate("MainWindow", "Ifover"))
